### PR TITLE
Corrected diagnostic to diagnose

### PR DESCRIPTION
**Pull request by timlyo**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a31dff19401da0953528f9489980a51c235dda75
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zitsen/unqlite.rs

---
This message was auto-generated by https://gitcop.com

**Comment by timlyo** [comment]
I'm not seeing any guidelines, do I need to give GitCop a doughnut?

**Comment by zitsen** [comment]
@timlyo Not need, I'll check, thank you.

**Comment by timlyo** [comment]
If you want to enforce some sort of contribution guidelines, you should probably write a contributing.md document so that people know what rules to follow.

**Pull request merged**
